Book/views/author_views.py
from flask import Blueprint , render_template,url_for,request,flash,session,g
from werkzeug.security import generate_password_hash, check_password_hash
from Book.forms import AuthorForm
from Book.Naverbookapiauth import Naverbookauth
import json
bp = Blueprint('author', __name__, url_prefix='/author')

@bp.route('/authorsearch/',methods=('POST','GET'))
def authorsearch():
    form= AuthorForm()
    if request.method == 'POST' and form.validate_on_submit():
        result = Naverbookauth(form.subject.data)
        result = json.loads(result)

        return render_template('/author/authorsearch.html',book_info_list=result['items'],  form=form)
    return render_template('/author/authorsearch.html',form=form)

Book/views/chatbotviews.py
from flask import Blueprint , render_template,url_for,request,flash,session,g
from werkzeug.security import generate_password_hash, check_password_hash


from datetime import datetime
from werkzeug.utils import redirect

bp= Blueprint('chatbot',__name__,url_prefix='/chatbot')

@bp.route('/book',methods=('GET',))
def chatbot():
    return render_template('chatbot/chatbot.html')

Book/views/helpbot_views.py
from flask import Blueprint , render_template,url_for,request,flash,session,g
from werkzeug.security import generate_password_hash, check_password_hash
from flask import Blueprint
from Book.dialogflowapi import dialogflow_chat
from datetime import datetime
from werkzeug.utils import redirect
from flask import Blueprint,request
import json
from Book import db
from Book.models import webhook
from flask import Blueprint
from Book.dialogflowapi import dialogflow_chat
from Book.forms import HelpbotForm

bp= Blueprint('helpbot',__name__,url_prefix='/helpbot')

@bp.route('/helpbot',methods=('POST','GET'))
def helpchat():
    form = HelpbotForm()
    if request.method == 'POST' and form.validate_on_submit():
        result = dialogflow_chat(form.subject.data)
        intent=result.query_result.intent.display_name
        if intent =='Bookname':
            return redirect(url_for('bookname.namesearch'))
        elif intent =='author':
            return redirect(url_for('author.authorsearch'))
        elif intent =='moviename':
            return redirect(url_for('movie.movieinfo'))
        elif intent =='movierank':
            return redirect(url_for('movie.movieranking'))
        elif intent =='shopping':
            return redirect(url_for('shopping.buysearch'))



    return render_template('chatbot/helpbot.html',form=form)

Book/views/movie_views.py
from flask import Blueprint , render_template,url_for,request,flash,session,g
import json
from Book.forms import MovieForm,RankForm
from Book.Movie import Movie
from Book.Movierank import movierank

bp = Blueprint('movie', __name__, url_prefix='/movie')

@bp.route('/info/',methods=('POST','GET'))
def movieinfo():
    form = MovieForm()
    if request.method == 'POST' and form.validate_on_submit():
        result = Movie(form.subject.data)
        result = json.loads(result)
        return render_template('movie.html', book_info_list=result['items'], form=form)
    return render_template('movie.html', form=form)



@bp.route('/rank/',methods=('POST','GET'))
def movieranking():
    form = RankForm()
    if request.method == 'POST' and form.validate_on_submit():
        result = movierank(form.subject.data)
        return render_template('movierank.html', rank_list=result, form=form)
    return render_template('movierank.html', form=form)

Book/views/moviechatviews.py
from flask import Blueprint , render_template,url_for,request,flash,session,g
from werkzeug.security import generate_password_hash, check_password_hash


from datetime import datetime
from werkzeug.utils import redirect

bp= Blueprint('moviechat',__name__,url_prefix='/moviechat')

@bp.route('/moviechatbot',methods=('GET',))
def moviechat():
    return render_template('chatbot/moviechatbot.html')

Book/views/shopping_views.py
from flask import Blueprint , render_template ,request, url_for
from werkzeug.utils import redirect
from datetime import datetime
import json
from Book.forms import BuyForm,ShopbuyForm
from Book.NaverShopping import Navershop
from Book import db
from Book.models import Buy

bp = bp = Blueprint('shopping', __name__, url_prefix='/shopping')

@bp.route('/search/',methods=('POST','GET'))
def buysearch():
    form = BuyForm()
    if request.method == 'POST' and form.validate_on_submit():
        result = Navershop(form.subject.data)
        result = json.loads(result)
        return render_template('shopping.html', shop_info_list=result['items'], form=form)
    return render_template('shopping.html', form=form)

@bp.route('/buy',methods=('POST','GET'))
def buy():
    form = ShopbuyForm()
    stitle=request.form['title']
    slprice=request.form['lprice']
    if request.method == "POST" and form.validate_on_submit():
        q = Buy(subject=stitle, content=form.content.data,price=slprice, create_date=datetime.now())
        db.session.add(q)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('shop_buy.html',form=form,title=stitle,lprice=slprice)

Book/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">

    <title>Book 입니다.</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">책과 영화정보</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
         <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{url_for('bookname.namesearch')}}">책이름 검색</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{url_for('author.authorsearch')}}">작가 검색</a>
            </li>
             <li class="nav-item ">
                <a class="nav-link" href="{{url_for('movie.movieinfo')}}">영화 정보</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{url_for('movie.movieranking')}}">영화 순위</a>
            </li>
             <li class="nav-item ">
                <a class="nav-link" href="{{url_for('shopping.buysearch')}}">상품 검색</a>
            </li>
             <li class="nav-item ">
                <a class="nav-link" href="{{url_for('chatbot.chatbot')}}">책 챗봇</a>
            </li>
              <li class="nav-item ">
                <a class="nav-link" href="{{url_for('moviechat.moviechat')}}">영화 챗봇</a>
            </li>
             <li class="nav-item ">
                <a class="nav-link" href="{{url_for('weatherchat.weatherchat')}}">날씨 챗봇</a>
            </li>
             <li class="nav-item ">
                <a class="nav-link" href="{{url_for('trotchat.trotchat')}}">미스터트롯 투표 챗봇</a>
            </li>
             <li class="nav-item ">
                <a class="nav-link" href="{{url_for('helpbot.helpchat')}}">사이트 도우미</a>
            </li>
        </ul>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

Book/templates/home.html
<h1> [붓꽃예측] </h1>

<form action="/" method="post">


<label >[입력]꽃받침 길이</label> </td>
<input type="text" name="Sepal_length"> </td>


		<label >[입력]꽃받침 너비</label> </td>
		<input type="text" name="Sepal_width"> </td>



	 <label >[입력]꽃잎 길이</label> </td>
	<input type="text" name="Petal_length"> </td>


	<label >[입력]꽃잎 너비</label> </td>
	<input type="text" name="Petal_width"> </td>


	<p> <button style="font-family: 'Nanum Barun Gothic' !important;" type="submit" >예측하기</button> </p>
</form>


<h2> [예측 결과]</h2>
	{% if result %}
	<h3 > {{ result }}</h3>
    {% endif %}

Book/templates/movie.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static',filename='bootstrap.min.css')}}">

<div class="container">
    <h5 class="my-3 border-button pb-2">영화정보 검색하기</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}


        {{ form.subject.label }}
        {{ form.subject(class="form-control") }}



        <button type="submit" class="btn btn-primary my-2">검색</button>
    </form>
</div>
{% if book_info_list %}
<div class="container my-3">
    <table class="table table-hover " style="font-size: 12px" >
        <thead>
            <tr class="text-center thead-dark">
                <th style="width: 10%">번호</th>
                <th style="width: 30%">제목</th>
                <th style="width: 15%">감독</th>
                <th style="width: 20%">배우</th>
                <th style="width: 15%">개봉년도</th>
                <th style="width: 10%">평점</th>
            </tr>
        </thead>
        <tbody>
        {% for temp in book_info_list %}
        <tr class="text-center">
             <td>{{ loop.index }}</td>
             <td>{{ temp.title | safe }}</td>
             <td>{{ temp.director | safe | shortword }}</td>
             <td>{{ temp.actor | safe | shortword }}</td>
             <td>{{ temp.pubDate | safe }}</td>
             <td>{{ temp.userRating | safe }}</td>
         </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}


{% endblock %}

Book/templates/movierank.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static',filename='bootstrap.min.css')}}">

<div class="container">
    <h5 class="my-3 border-button pb-2">영화순위 검색하기</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}


        {{ form.subject.label }}
        {{ form.subject(class="form-control") }}



        <button type="submit" class="btn btn-primary my-2">검색</button>
    </form>
</div>
{% if rank_list %}
<div class="container my-3">
    <table class="table table-hover " style="font-size: 12px" >
        <thead>
            <tr class="text-center thead-dark">
                <th style="width: 10%">순위</th>
                <th style="width: 90%">제목</th>

            </tr>
        </thead>
        <tbody>
        {% for temp in rank_list %}
        <tr class="text-center">
             <td>{{ loop.index }}</td>
             <td>{{ temp | safe }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}


{% endblock %}

Book/templates/shop_buy.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static',filename='bootstrap.min.css')}}">

<div class="container">
    <h5 class="my-3 border-button pb-2">주소</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}
        {{ form.content.label }}
        {{ form.content(class="form-control") }}
    <input type="hidden" name="title" value={{title}}>
                <input type="hidden" name="lprice" value={{lprice}}>
        <button type="submit" class="btn btn-primary my-2">입력</button>
    </form>
</div>

{% endblock %}

Book/templates/shopping.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static',filename='bootstrap.min.css')}}">

<div class="container">
    <h5 class="my-3 border-button pb-2">상품명</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}


        {{ form.subject.label }}
        {{ form.subject(class="form-control") }}



        <button type="submit" class="btn btn-primary my-2">검색</button>
    </form>
</div>
{% if shop_info_list %}
<div class="container my-3">
    <table class="table table-hover " style="font-size: 12px" >
        <thead>
            <tr class="text-center thead-dark">
                <th style="width: 10%">번호</th>
                <th style="width: 30%">상품명</th>
                <th style="width: 15%">브랜드</th>
                <th style="width: 15%">최저가</th>
                <th style="width: 15%">최고가</th>
                <th style="width: 15%">이미지</th>
            </tr>
        </thead>
        <tbody>
        {% for temp in shop_info_list %}
        <tr class="text-center">
             <td>{{ loop.index }}</td>
             <td>{{ temp.title | safe }}</td>
             <td>{{ temp.brand | safe  }}</td>
             <td>{{ temp.lprice | safe }}</td>
             <td>{{ temp.hprice | safe }}</td>
             <td><img src={{ temp.image }} height="100" width="100" alt="제품이미지"></img></td>
            <td><form action="{{ url_for('shopping.buy')}}" method="post" class="post-form my-3 ml-3">
                <input type="hidden" name="title" value={{temp.title}}>
                <input type="hidden" name="lprice" value={{temp.lprice}}>
                <input type="submit" value="구매" class="btn btn-primary"></form></td>
         </tr>

        {% endfor %}
        </tbody>
    </table>

</div>
{% endif %}


{% endblock %}