Book/views/bookname_views.py
from flask import Blueprint , render_template,url_for,request,flash,session,g
from werkzeug.security import generate_password_hash, check_password_hash
from Book.forms import BooknameForm,ShopbuyForm
from Book.Naverbookapi import Naverbook
import json
from datetime import datetime
from Book.models import Buy
from Book import db
from werkzeug.utils import redirect

bp = Blueprint('bookname', __name__, url_prefix='/bookname')

@bp.route('/namesearch/',methods=('POST','GET'))
def namesearch():
    form = BooknameForm()
    if request.method == 'POST' and form.validate_on_submit():
        result = Naverbook(form.subject.data)
        result = json.loads(result)

        return render_template('/bookname/namesearch.html', book_info_list=result['items'], form=form)


    return render_template('/bookname/namesearch.html',form=form)

@bp.route('/bookbuy',methods=('POST','GET'))
def bookbuy():
    form = ShopbuyForm()
    btitle = request.form['title']
    if request.method == "POST" and form.validate_on_submit():
        q = Buy(subject=btitle, content=form.content.data, name=form.name.data, create_date=datetime.now())
        db.session.add(q)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('/bookname/book_buy.html', form=form, title=btitle)

Book/templates/bookname/book_buy.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static',filename='bootstrap.min.css')}}">

<div class="container">
    <h5 class="my-3 border-button pb-2">이름/주소를 입력해주세요</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}
        {{ form.name.label }}
        {{ form.name(class="form-control") }}
        {{ form.csrf_token }}
        {{ form.content.label }}
        {{ form.content(class="form-control") }}
        <input type="hidden" name="title" value={{title}}>
    <button type="submit" class="btn btn-primary my-2">입력</button>
        </form>
</div>

{% endblock %}

Book/templates/bookname/namesearch.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static',filename='bootstrap.min.css')}}">

<div class="container">

    <h5 class="my-3 border-button pb-2">책이름으로 검색/구매하는 창입니다. 책제목을 입력해주세요.</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}


        {{ form.subject.label }}
        {{ form.subject(class="form-control") }}



        <button type="submit" class="btn btn-primary my-2">검색</button>
    </form>
</div>
{% if book_info_list %}
<div class="container my-3">
    <table class="table table-hover " style="font-size: 12px" >
        <thead>
            <tr class="text-center thead-dark">
                <th style="width: 10%">번호</th>
                <th style="width: 40%">제목</th>
                <th style="width: 40%">내용</th>
                <th style="width: 10%">작가</th>
            </tr>
        </thead>
        <tbody>
        {% for temp in book_info_list %}
        <tr class="text-center">
             <td>{{ loop.index }}</td>
             <td>{{ temp.title | safe }}</td>
             <td>{{ temp.description | safe | shortword }}</td>
             <td>{{ temp.author | safe | shortword }}</td>
         <td><form action="{{ url_for('bookname.bookbuy')}}" method="post" class="post-form my-3 ml-3">
                <input type="hidden" name="title" value={{temp.title}}>
                <input type="submit" value="구매" class="btn btn-primary"></form></td>
         </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}